### ISSUE TITLE
No longer working with Ecto 2.0-beta

### ISSUE THREAD

**Issue by johnhamelink** [vic/params#1]
Hey there,

The breaking changes introduced in 2.0-beta have caused params to break (thankfully its tests also break in the same way). I'm working on a PR to fix this right now, but in the meantime, here's the sort of errors I'm experiencing:

```elixir
Compiled lib/params/def.ex
** (Protocol.UndefinedError) protocol Enumerable not implemented for :id
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1486: Enum.reduce/3
    test/params_test.exs:10: (module)
    test/params_test.exs:8: (module)
```

```elixir
== Compilation error on file lib/params.ex ==
** (CompileError) lib/params.ex:77: unknown key :model for struct Ecto.Changeset
    (elixir) src/elixir_map.erl:185: :elixir_map."-assert_struct_keys/5-lc$^0/1-0-"/5
    (elixir) src/elixir_map.erl:62: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

**Comment by johnhamelink** [comment]
Some information @mitchellhenke and I have gathered over Slack:

 - Changes to `%Ecto.Changeset{}` between 1.x and 2.x:  https://gist.github.com/sorentwo/9b351ead9fbc2c7da500
 - Issue seems to be associated with parsing the *field*, not the *schema*, although due to macros, the stacktrace doesn't make this clear.

**Comment by vic** [comment]
Hey, thanks for your work on getting this working with ecto 2.

I've created a new branch `ecto-2.x` and released [a new version](https://hex.pm/packages/params/2.0.0-beta.0)

I'll merge on master as soon as ecto 2 gets out of beta.

**Comment by johnhamelink** [comment]
@vic you are a beautiful human being :smile: Thanks for putting this out so quickly!
